### ISSUE TITLE
关于配置实时更新的问题

### ISSUE THREAD

**Issue by zgqyfj** [zhudyos/duic#16]
请问一下配置实时更新的实现,是通过client实时发送http请求根据state的值判断是否重载来实现的么

**Comment by kevin70** [comment]
https://github.com/zhudyos/duic/wiki/duic_design&impl#%E9%85%8D%E7%BD%AE%E5%AE%9E%E6%97%B6%E6%9B%B4%E6%96%B0

通过上面的文档可了解详细的实现细节。
