### ISSUE TITLE
怎样迁移

### ISSUE THREAD

**Issue by dongasai** [zhudyos/duic#5]
如题

**Comment by kevin70** [comment]
从何处迁移？

**Comment by dongasai** [comment]
比如我在公司内有个环境,测试的,现在测试结束了,要上线到阿里云

**Comment by dongasai** [comment]
还没有开始使用

**Comment by kevin70** [comment]
我猜想你可能是需要 duic 部署相关的内容，你可以参考文档 https://github.com/zhudyos/duic/wiki/deployment
